# Generated by Django 4.1.3 on 2022-11-19 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='takenotes',
            name='important',
            field=models.CharField(default=0, max_length=3),
            preserve_default=False,
        ),
    ]
