# Generated by Django 4.1.3 on 2022-11-19 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_takenotes_important'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phonenumber', models.IntegerField(max_length=10)),
                ('email', models.EmailField(max_length=50)),
                ('issue', models.CharField(max_length=300)),
            ],
        ),
    ]
